name: Publicar Docs

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instala dependencias
        run: |
          pip install mkdocs-material mkdocstrings[python] pymdown-extensions mkdocs-mermaid2-plugin

      - name: Publica en GitHub Pages
        run: mkdocs gh-deploy --force
